// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBW04pir802MNX34wCRpF6WQ4LOOXWchzs',
    appId: '1:742951082421:web:2caa77ca2c9b7207c261fc',
    messagingSenderId: '742951082421',
    projectId: 'hamma-khdamat',
    authDomain: 'hamma-khdamat.firebaseapp.com',
    storageBucket: 'hamma-khdamat.appspot.com',
    measurementId: 'G-LVBZ8YW05B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_NWoNTtmQJxG0TZ3hfPczkqo1h-W8u_k',
    appId: '1:742951082421:android:050b3e7400fb2e67c261fc',
    messagingSenderId: '742951082421',
    projectId: 'hamma-khdamat',
    storageBucket: 'hamma-khdamat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBp4Iqo7UnUV-EJCXeEjBKxpVv_SWCQN1I',
    appId: '1:742951082421:ios:2bc1eff1270b431bc261fc',
    messagingSenderId: '742951082421',
    projectId: 'hamma-khdamat',
    storageBucket: 'hamma-khdamat.appspot.com',
    iosBundleId: 'com.fnrco.hamma',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBp4Iqo7UnUV-EJCXeEjBKxpVv_SWCQN1I',
    appId: '1:742951082421:ios:249c2d7741549d10c261fc',
    messagingSenderId: '742951082421',
    projectId: 'hamma-khdamat',
    storageBucket: 'hamma-khdamat.appspot.com',
    iosBundleId: 'com.fnrco.musaneda',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBW04pir802MNX34wCRpF6WQ4LOOXWchzs',
    appId: '1:742951082421:web:652a455c8b4d1156c261fc',
    messagingSenderId: '742951082421',
    projectId: 'hamma-khdamat',
    authDomain: 'hamma-khdamat.firebaseapp.com',
    storageBucket: 'hamma-khdamat.appspot.com',
    measurementId: 'G-S3E7YSQXKP',
  );
}
